modLoader="javafml"
loaderVersion="${loader_version_range}"
license="Unlicense"

[[mods]]
modId="blahaj"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://wavee.dog"
logoFile="icon.png"
enumExtensions="META-INF/enumextensions.json"
credits="Made by Hibi"
authors="${mod_authors}"
description='''
Soft toy, shark mod, 16px.
'''

[[dependencies.blahaj]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blahaj]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
